[package]
name = "actix-swagger"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.0"
actix-web-httpauth = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
utoipa = { version = "5.4.0" }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
